### PR TITLE
Allow waitforservices to be used on alpine by disabling the glibc requirement

### PR DESCRIPTION
**Pull request by SerialVelocity**

### CODE REVIEW

**Comment by SerialVelocity** [comment]
Fixes a blocking issue for us.

**Comment by tobischo** [comment]
I understand the `CGO_ENABLED=0` change
Why did you also change the volume mount? Not everyone may want to mount `/home/docker/waitforservices` (or even have that directory)

**Comment by SerialVelocity** [comment]
Whoops, let me fix that. That was because I had to scp the folder to my docker machine.

**Comment by SerialVelocity** [comment]
@tobischo There you go. This should be fine now. Is it possible to tag a new release after this merges?

**Comment by tobischo** [comment]
Yes, that should be possible, can't promise that this will happen today though
@meeee will take care of it as soon as there is time
This will probably be in a release together with https://github.com/Barzahlen/waitforservices/pull/5 anyway

**Comment by mfrister** [comment]
@SerialVelocity Thanks!

**Comment by SerialVelocity** [comment]
@meeee You're welcome!
@tobischo Actually, it doesn't really matter anymore. We found a temporary workaround.

**Comment by mfrister** [comment]
Released [v0.4](https://github.com/Barzahlen/waitforservices/releases/tag/v0.4) anyway.

**Pull request merged**
